### ISSUE TITLE
duplicate data in DE scraper

### ISSUE THREAD

**Issue by sglyon** [covid-projections/can-scrapers#106]
I think we may have a bug in the Delaware scraper

The `Date` column seems to be set for each csv in the `fetch` method

Then in `normalize` we are using `dt=self._retrieve_dt("US/Eastern")` instead of that Date column

I _think_ the fix should be as simple as renaming `Date` -> `dt` in `.fetch` and then not trying to `assign` to `dt` in `.normalize`

@ChrisBremer does that sound right to you?

**Comment by sglyon** [comment]
For reference -- here is where we get `Date`: https://github.com/covid-projections/can-scrapers/blob/54d237da872c467e213bfd37c91af0ec3d20dddc/can_tools/scrapers/official/DE/de_state.py#L38

And here is where we set `dt`: https://github.com/covid-projections/can-scrapers/blob/54d237da872c467e213bfd37c91af0ec3d20dddc/can_tools/scrapers/official/DE/de_state.py#L110

**Comment by ChrisBremer** [comment]
Ah, great catch.  I think you or Chase commented on this in my AZ scraper
too - I had my *vintage* and *dt* purposes convoluted.  That's the right
fix from what I can see.  I've submitted a PR for the fixed version.

It also looks like when you or Chase converged my DE state and
county scrapers together (Looks so clean! Great job!) the data filter to
Max(date) was removed.  Do you guys want all of the days of historic data
pulled in every time this scraper runs?  If so, we can remove the filter to
max date I've added in line 45.

[image: image.png]

**Comment by cc7768** [comment]
Ooops -- I hadn't seen this discussion before merging :facepalm: 

It would be great to have the historic data downloaded every time. Sometimes they make adjustments to previous data. I'll put out a fix for this by removing the `max` that you added to the code.

**Comment by sglyon** [comment]
Thanks @ChrisBremer 

I didn't see the PR yet, perhaps you pushed the branch, but didn't open the PR?

Thanks

**Comment by sglyon** [comment]
Scratch that last comment, you and @cc7768 already took care of it!

Good work!

**Comment by sglyon** [comment]
@cc7768 I removed the filter on max date and pushed to master
