### ISSUE TITLE
Oklahoma

### ISSUE THREAD

**Issue by sglyon** [covid-projections/can-scrapers#47]

**Comment by zweissman** [comment]
This looks to be a total re-write. The historical script was just getting data from ARCGIS for Tulsa county. But it looks like there is data for all counties now

https://looker-dashboards.oklahoma.gov/embed/dashboards/63

**Comment by sglyon** [comment]
Thanks @zweissman!

This one looks like it will be a great second PR for someone. They offer downloadable files and it will hopefully be pretty easy to get it integrated once the PR author is familiar with the our scraper system
